import Images, {
  Images2,
  Images3,
  Images4,
  Images5,
  Images6,
  Images7,
  Images8,
  Image10,
  Images11,
  Images12,
  Images13,
  Image14,
  Image15,
  Image16,
  Images17,
  Images18,
  Image19,
  Image20,
  Image21,
  Image22,
  Image23,
  Images24,
  Images25,
  Images26,
  Images27,
  Images28,
  Images9,
} from "../utils/img";

const Productss = [
  {
    id: 1,
    image: Images.hHarness,
    thumbnails: [
      Images.hHarness1,
      Images.hHarness2,
      Images.hHarness3,
      Images.hHarness4,
      Images.hHarness5,
      Images.hHarness6,
      Images.hHarness7,
      Images.hHarness8,
      Images.hHarness9,
    ],
    name: "H-Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 2,
    image: Images2.EasyOn,
    thumbnails: [
      Images2.EasyOn1,
      Images2.EasyOn2,
      Images2.EasyOn3,
      Images2.EasyOn4,
    ],
    name: "Easy On Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 3,
    image: Images3.fullBody1,
    thumbnails: [
      Images3.fullBody1,
      Images3.fullBody2,
      Images3.fullBody3,
      Images3.fullBody4,
      Images3.fullBody5,
      Images3.fullBody6,
      Images3.fullBody7,
      Images3.fullBody8,
      Images3.fullBody9,
      Images3.fullBody10,
      Images3.fullBody11,
      Images3.fullBody12,
      Images3.fullBody13,
    ],
    name: "Full Body Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 4,
    image: Images4.chest,
    thumbnails: [
      Images4.chest,
      Images4.chest1,
      Images4.chest2,
      Images4.chest3,
      Images4.chest4,
      Images4.chest5,
    ],
    name: "Chest Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 5,
    image: Images5.catHarness1,
    thumbnails: [
      Images5.catHarness1,
      Images5.catHarness2,
      Images5.catHarness3,
      Images5.catHarness4,
      Images5.catHarness5,
      Images5.catHarness6,
    ],
    name: "Cat Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 6,
    image: Images6.dogCollerA,
    thumbnails: [
      Images6.dogCollerA,
      Images6.dogColler1,
      Images6.dogColler2,
      Images6.dogColler3,
      Images6.dogColler4,
      Images6.dogColler5,
      Images6.dogColler6,
      Images6.dogColler7,
      Images6.dogColler8,
      Images6.dogColler9,
      Images6.dogColler10,
      Images6.dogColler11,
      Images6.dogColler12,
      Images6.dogColler13,
      Images6.dogColler14,
      Images6.dogColler15,
      Images6.dogColler16,
      Images6.dogColler17,
      Images6.dogColler18,
      Images6.dogColler19,
    ],
    name: "Dog Collar",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 7,
    image: Images7.dogCollar4,
    thumbnails: [
      Images7.dogCollar2,
      Images7.dogCollar3,
      Images7.dogCollar4,
      Images7.dogCollar5,
      Images7.dogCollar6,
      Images7.dogCollar7,
      Images7.dogCollar8,
      Images7.dogCollar9,
      Images7.dogCollar10,
      Images7.dogCollar11,
      Images7.dogCollar12,
      Images7.dogCollar13,
      Images7.dogCollar1,
    ],
    name: "Dog Collar Printed",
    category: "WALKING ESSENTIALS",
  },

  {
    id: 8,
    image: Images8.leashA,
    thumbnails: [
      Images8.leash1,
      Images8.leash2,
      Images8.leash3,
      Images8.leash4,
    ],
    name: "Leash",
    category: "WALKING ESSENTIALS",
  },

  {
    id: 9,
    image: Images9.jacket,
    thumbnails: [
      Images9.jacket,
      Images9.jacket1,
      Images9.jacket2,
      Images9.jacket3,
      Images9.jacket4,
      Images9.jacket5,
      Images9.jacket6,
      Images9.jacket7,
      Images9.jacket8,
      Images9.jacket9,
      Images9.jacket10,
      Images9.jacket11,
    ],
    name: "Jacket",
    category: "JACKETS",
  },
  {
    id: 10,
    image: Image10.Basket,
    thumbnails: [
      Image10.Basket,
      Image10.Basket1,
      Image10.Basket2,
      Image10.Basket3,
      Image10.Basket4,
    ],
    name: "Step-In Harness/ Basket Harness",
    category: "WALKING ESSENTIALS",
  },
  {
    id: 11,
    image: Images11.tuxedo1,
    thumbnails: [
      Images11.tuxedo1,
      Images11.tuxedo2,
      Images11.tuxedo3,
      Images11.tuxedo4,
    ],
    name: "Tuxedo",
    category: "WALKING ESSENTIALS",
  },

  {
    id: 12,
    image: Images12.bow_ties1,
    thumbnails: [
      Images12.bow_ties1,
      Images12.bow_ties2,
      Images12.bow_ties3,
      Images12.bow_ties4,
      Images12.bow_ties5,
      Images12.bow_ties6,
      Images12.bow_ties7,
      Images12.bow_ties8,
      Images12.bow_ties9,
      Images12.bow_ties10,
    ],
    name: "Bow Tue",
    category: ""
  },

  {
    id: 13,
    image: Images13.bandana,
    thumbnails: [
      Images13.bandana,
      Images13.bandana2,
      Images13.bandana3,
      Images13.bandana4,
      Images13.bandana5,
      Images13.bandana6,
      Images13.bandana7,
      Images13.bandana8,
      Images13.bandana9,
      Images13.bandana10,
      Images13.bandana11,
      Images13.bandana12,
      Images13.bandana13,
      Images13.bandana14,
    ],
    name: "Bandana",
    category: "",
  },

  {
    id: 14,
    image: Image14.PrintedMat,
    thumbnails: [
      Image14.PrintedMat,
      Image14.PrintedMat1,
      Image14.PrintedMat2,
      Image14.PrintedMat3,
      Image14.PrintedMat4,
      Image14.PrintedMat5,
      Image14.PrintedMat6,
      Image14.PrintedMat7,
      Image14.PrintedMat8,
      Image14.PrintedMat9,
      Image14.PrintedMat10,
      Image14.PrintedMat11,
      Image14.PrintedMat12,
      Image14.PrintedMat13,
      Image14.PrintedMat14,
      Image14.PrintedMat15,
      Image14.PrintedMat16,
      Image14.PrintedMat17,
    ],
    name: "Printed Mat",
    category: "BEDDING",
  },

  {
    id: 15,
    image: Image15.furMat,
    thumbnails: [
      Image15.furMat,
      Image15.furMat1,
      Image15.furMat2,
      Image15.furMat3,
    ],
    name: "Fur Mat",
    category: "BEDDING",
  },
  {
    id: 16,
    image: Image16.patternLounger,
    thumbnails: [
      Image16.patternLounger,
      Image16.patternLounger1,
      Image16.patternLounger2,
      Image16.patternLounger3,
      Image16.patternLounger4,
      Image16.patternLounger5,
      Image16.patternLounger6,
    ],
    name: "Pattern Lounger",
    category: "BEDDING",
  },
  {
    id: 17,
    image: Images17.EmbLounger,
    thumbnails: [
      Images17.EmbLounger,
      Images17.EmbLounger2,
      Images17.EmbLounger3,
    ],
    name: "Embroidery Lounger",
    category: "BEDDING",
  },
  {
    id: 18,
    image: Images18.furLounger,
    thumbnails: [
      Images18.furLounger,
      Images18.furLounger1,
      Images18.furLounger2,
      Images18.furLounger3,
      Images18.furLounger4,
      Images18.furLounger5,
      Images18.furLounger6,
      Images18.furLounger7,
      Images18.furLounger8,
      Images18.furLounger9,
      Images18.furLounger10,
      Images18.furLounger11,
      Images18.furLounger12,
      Images18.furLounger13,
      Images18.furLounger14,
    ],
    name: "Fur Lounger",
    category: "BEDDING",
  },
  {
    id: 19,
    image: Image19.printLounger,
    thumbnails: [
      Image19.printLounger,
      Image19.printLounger1,
      Image19.printLounger2,
      Image19.printLounger3,
      Image19.printLounger4,
      Image19.printLounger5,
      Image19.printLounger6,
      Image19.printLounger7,
      Image19.printLounger8,
      Image19.printLounger9,
      Image19.printLounger10,
      Image19.printLounger11,
    ],
    name: "Printed Lounger",
    category: "BEDDING",
  },
  {
    id: 20,
    image: Image20.Mattress,
    thumbnails: [
      Image20.Mattress,
      Image20.Mattress1,
      Image20.Mattress2,
      Image20.Mattress3,
      Image20.Mattress4,
    ],
    name: "Mattress",
    category: "BEDDING",
  },
  {
    id: 21,
    image: Image21.RoundBed1,
    thumbnails: [
      Image21.RoundBed,
      Image21.RoundBed1,
      Image21.RoundBed2,
      Image21.RoundBed3,
      Image21.RoundBed4,
      Image21.RoundBed5,
      Image21.RoundBed6,
    ],
    name: "Round Bed",
    category: "BEDDING",
  },
  {
    id: 22,
    image: Image22.hutSnail,
    thumbnails: [
      Image22.hutSnail,
      Image22.hutSnail2,
      Image22.hutSnail3,
      Image22.hutSnail4,
      Image22.hutSnail5,
      Image22.hutSnail6,
    ],
    name: "Hut-Snail",
    category: "CAVE HUT",
  },
  {
    id: 23,
    image: Image23.hutPumpkin,
    thumbnails: [
      Image23.hutPumpkin,
      Image23.hutPumpkin1,
      Image23.hutPumpkin2,
      Image23.hutPumpkin3,
      Image23.hutPumpkin4,
      Image23.hutPumpkin5,
      Image23.hutPumpkin6,
      Image23.hutPumpkin7,
    ],
    name: "Hut-Pumpkin",
    category: "CAVE HUT"
  },
  {
    id: 24,
    image: Images24.hutCaterpillar4,
    thumbnails: [
      Images24.hutCaterpillar,
      Images24.hutCaterpillar2,
      Images24.hutCaterpillar3,
      Images24.hutCaterpillar4,
    ],
    name: "Hut-Caterpillar",
    category: "CAVE HUT"
  },

  {
    id: 25,
    image: Images25.bedCartoon,
    thumbnails: [
      Images25.bedCartoon,
      Images25.bedCartoon1,
      Images25.bedCartoon2,
    ],
    name: "Cave Bed-Cartoon",
    category: "CAVE HUT"
  },
  {
    id: 26,
    image: Images26.xmas2,
    thumbnails: [Images26.xmas, Images26.xmas1, Images26.xmas2],
    name: "Cave Bed-X-MAS",
    category: "CAVE HUT"
  },
  {
    id: 27,
    image: Images27.hutGray,
    thumbnails: [Images27.hutGray, Images27.hutGray1, Images27.hutGray2],
    name: "Cave Bed-Grey",
    category: "CAVE HUT"
  },
  {
    id: 28,
    image: Images28.hutPrinted1,
    thumbnails: [
      Images28.hutPrinted,
      Images28.hutPrinted1,
      Images28.hutPrinted2,
      Images28.hutPrinted3,
      Images28.hutPrinted4,
      Images28.hutPrinted5,
      Images28.hutPrinted6,
      Images28.hutPrinted7,
    ],
    name: "Cave Bed-Printed",
    category: ["CAVE HUT" , "JACKET"]
  },
];

export default Productss;
